-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O LEFT OUTER JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE (O.ANIMAL_ID, O.NAME) NOT IN (SELECT ANIMAL_ID, NAME FROM ANIMAL_INS)
ORDER BY I.ANIMAL_ID