-- 코드를 작성해주세요
WITH SCORE_SUM AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
               
SELECT S.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM HR_EMPLOYEES E JOIN SCORE_SUM S ON E.EMP_NO = S.EMP_NO
WHERE S.SCORE = (SELECT MAX(SCORE) FROM SCORE_SUM)

